on:
  workflow_dispatch:
    branches: [main]
  schedule:
  - cron: '*/5 * * * *'

name: 04-run-r-script

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::pkgload
      - name: run-script
        run: Rscript inst/rodar-gpt3.R

      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Atualiza arquivos - por 04-r-script" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
